### ISSUE TITLE
Battery loading incorrect after using Battery Calibration

### ISSUE THREAD

**Issue by bege10** [Perflyst/BatteryCalibration#5]
After using BatteryCalibration the loading process remains at 94% saying 11 minutes left unti full - loading is never ending. The only workaraound I found is to reboot into recovery and finish loading there.
How can I fix this?
Samsung Galaxy S5 Plus (SM-G901F) with LineageOS 15.1 (Android 8.1), NanoDroid (microG)

**Comment by TacoTheDank** [comment]
having this little issue as well on my HTC One M7

**Comment by Perflyst** [comment]
@TacoTheDank which android version are you running?

**Comment by bege10** [comment]
Meanwhile I found this issue also in a German LineageOS-Forum. There they assume it is an issue with a new OS-update. Perhaps it is just a coincidence with the usage of BatteryCalibration. I will come back when I now more.

**Comment by bege10** [comment]
Several posts in this thread look like it is an issue of Samsung and LineageOS, not of BatteryCalibration.
https://forum.xda-developers.com/showpost.php?p=78264212&postcount=1869

**Comment by TacoTheDank** [comment]
@Perflyst 
- Android 5.0.2
- Using ROM that came with phone
- Unlocked bootloader and rooted
- System-write protection is still on, so I can't uninstall bloatware because it comes right back (have to flash stuff through TWRP)
- Not related, but I have to use SuperSU instead of Magisk because Magisk never prompts me to grant/deny, it just stalls whenever an app requests it (and also stalls the app). Magisk Manager itself works fine when installing modules and can make the phone reboot and do other stuff it's supposed to

Only one of these is really actually relevant but eh lmao

Also the issue on my phone isn't exactly what OP described. It's more that the battery percentage shown is constantly inconsistent with the actual amount of battery left. Like battery percentage can be at 40% and then the phone dies, and when it is plugged in after said death, the percentage on the charging screen shows like 4% or something similar. Also the percentage shown when the phone is booted up stays at said percentage for quite a while, when in reality the battery is decreasing but not being shown as decreasing in the icon or settings or anything.

**Comment by bege10** [comment]
Solved with new updates of LineageOS.

**Comment by Perflyst** [comment]
Can you provide a link to the specific changelog?

**Comment by bege10** [comment]
There have been three patches, here are two of them
https://review.lineageos.org/236551
https://review.lineageos.org/235724
In this forum is the discussion about it
https://forum.xda-developers.com/galaxy-s5/development/rom-lineage-os-samsung-galaxy-s5-lte-t3534283
